set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1141.050 -nets VDD -layer 18 -width 0.680 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 0.870 -nets VDD -layer 18 -width 0.680 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.050 -nets VDD -layer 19 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1138.950 -nets VDD -layer 19 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1140.130 -nets VSS -layer 18 -width 0.680 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.790 -nets VSS -layer 18 -width 0.680 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.620 -nets VSS -layer 19 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1137.380 -nets VSS -layer 19 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 38.510 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 75.310 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 112.110 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 148.590 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 185.390 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 222.190 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 258.670 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 295.470 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 332.270 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 368.750 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 405.550 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 442.350 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 478.830 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 515.630 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 552.430 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 588.910 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 625.710 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 662.510 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 698.990 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 735.790 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 772.270 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 809.070 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 845.870 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 882.350 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 919.150 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 955.950 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 992.430 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1029.230 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1066.030 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1102.510 -nets VDD  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1139.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 39.090 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 75.890 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 112.690 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 149.170 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 185.970 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 222.770 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 259.250 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 296.050 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 332.850 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 369.330 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 406.130 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 442.930 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 479.410 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 516.210 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 553.010 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 589.490 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 626.290 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 663.090 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 699.570 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 736.370 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 772.850 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 809.650 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 846.450 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 882.930 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 919.730 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 956.530 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 993.010 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1029.810 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1066.610 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1103.090 -nets VSS  -layer 18 -width 0.340 -pitch_within_group 36.690 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 1137.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 39.370 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 75.370 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 112.270 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 149.170 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 185.170 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 222.070 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 258.970 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 294.970 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 331.870 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 367.870 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 404.770 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 441.670 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 477.670 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 514.570 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 551.470 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 587.470 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 624.370 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 661.270 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 697.270 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 734.170 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 770.170 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 807.070 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 843.970 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 879.970 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 916.870 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 953.770 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 989.770 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1026.670 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1063.570 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1099.570 -nets VDD  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 1141.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 40.430 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.430 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 113.330 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 150.230 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 186.230 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 223.130 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 260.030 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 296.030 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 332.930 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 368.930 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 405.830 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 442.730 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 478.730 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 515.630 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 552.530 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 588.530 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 625.430 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 662.330 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 698.330 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 735.230 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 771.230 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 808.130 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 845.030 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 881.030 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 917.930 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 954.830 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 990.830 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1027.730 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1064.630 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1100.630 -nets VSS  -layer 19 -width 0.520 -pitch_within_group 36.570 -start_low_ends coordinate  -start_low_ends_coordinate 1.450 -start_high_ends coordinate  -start_high_ends_coordinate 1140.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
